### ISSUE TITLE
Libraries do not load on Windows

### ISSUE THREAD

**Issue by ltouroumov** [libly/resource-loader#3]
Trying to load a library on Windows crashes with a `NullPointerException` in [ResourceLoader.java @ L135](https://github.com/libly/resource-loader/blob/master/src/main/java/co/libly/resourceloader/ResourceLoader.java#L135). The cause seems to be these lines of code ([L64](https://github.com/libly/resource-loader/blob/master/src/main/java/co/libly/resourceloader/ResourceLoader.java#L64)):

```java
// If the file does not start with a separator,
// then let's make sure it does!
if (!relativePath.startsWith(File.separator)) {
    relativePath = File.separator + relativePath;
}
```

On Windows `File.separator` is `\` which poses a problem when loading with `Class.getResource` since the URL expects a `/`.

**Comment by gurpreet-** [comment]
Hi @ltouroumov,

Thanks for the bug report. Good catch! 

It seems like your PR was submitted to merge into your own repo's `master` branch and not Resource Loader's master branch 🙂 Please raise your PR against Resource Loader's `master` branch then I'll approve and merge!

Thanks!
